# Unique project name
name: obs-deps-buildstream

# Required BuildStream version
min-version: 2.5

aliases:
  (@): include/_private/aliases.yml

(@): include/runtime.yml

# Subdirectory where elements are stored
element-path: elements

fatal-warnings:
- overlaps
- unaliased-url

options:
  target_arch:
    type: arch
    description: Target Architecture
    variable: target_arch
    values:
    - x86_64
    - aarch64
  platform:
    type: enum
    description: Target Platform
    variable: platform
    values:
    - flatpak
    default: flatpak

sandbox:
  build-arch: '%{target_arch}'

variables:
  source-date-epoch: '1380562633'

  license-files-extra: >-
    LICENSES/*.txt

environment:
  (@): include/_private/environment.yml

  SOURCE_DATE_EPOCH: '%{source-date-epoch}'

split-rules:
  (@): include/_private/split-rules.yml

elements:
  autotools:
    (@): include/_private/autotools-conf.yml
  cmake:
    (@): include/_private/cmake-conf.yml
  meson:
    (@): include/_private/meson-conf.yml

sources:
  pypi:
    (@): include/_private/pypi.yml

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  elements:
  - autotools
  - cmake
  - make
  - meson
  sources:
  - patch

- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  elements:
  - collect_manifest
  - pyproject
  sources:
  - git_repo
  - git_tag
  - pypi
