name: Sync shared Freedesktop SDK files
description: Synchronize files copied from Freedesktop SDK BuildStream
inputs:
  fsdk-element:
    description: Freedesktop SDK BuildStream element
    default: freedesktop-sdk.bst
outputs:
  fsdk-element:
    description: Freedesktop SDK BuildStream element
    value: ${{ inputs.fsdk-element }}
  version:
    description: Version of Freedesktop SDK
    value: ${{ steps.sync.outputs.version }}
runs:
  using: composite
  steps:
    - name: Parse ref
      id: parse-ref
      shell: bash
      run: |
        python .github/scripts/parse-bst-git-tag-ref.py elements/${{ inputs.fsdk-element }}

    - name: Sync shared files
      id: sync
      shell: bash
      run: |
        git clone --branch=${{ steps.parse-ref.outputs.tag }} --depth=1 https://gitlab.com/freedesktop-sdk/freedesktop-sdk

        for file in elements/plugins/*; do
          if [ -f "freedesktop-sdk/$file" ]; then
            cp freedesktop-sdk/$file $file
          else
            rm $file
          fi
        done

        # Extract strip-binaries as strip-binaries-base
        sed -n '/strip-binaries: |/,/^$/{s/strip-binaries/&-base/g;p};1avariables:' \
          freedesktop-sdk/include/strip.yml > include/_private/fsdk-strip-binaries-base.yml

        # Extract FFmpeg dependencies
        sed -E -n '/^depends:$/,/^$/{s%(components|public-stacks)/%freedesktop-sdk.bst:&%g;p}' \
          freedesktop-sdk/elements/include/ffmpeg.yml > elements/include/_private/fsdk-ffmpeg-depends.yml

        # Copy element/include/ffmpeg.yml without depends, public and sources
        sed -E -n '0,/^variables:$/s%(components|public-stacks)/%freedesktop-sdk.bst:&%g;{/^depends:$/,/^$/d;/^public:$/,/^$/d;/^sources:$/,/^$/d;p}' \
          freedesktop-sdk/elements/include/ffmpeg.yml > elements/include/_private/ffmpeg.yml

        tag="${{ steps.parse-ref.outputs.tag }}"
        prefix="freedesktop-sdk-"
        version="${tag#$prefix}"

        echo "version=$version" >> $GITHUB_OUTPUT

        rm -rf freedesktop-sdk
