name: Build Project
on:
  workflow_call:
    inputs:
      arch:
        description: Architecture of the build
        default: x86_64
        type: string
      upload-artifacts:
        description: Upload generated artifacts
        default: false
        type: boolean
      reupload-cache:
        description: Re-upload the cache to avoid automatic eviction
        default: false
        type: boolean
env:
  FP_DEPS_KEY_PREFIX: flatpak-deps-bst-${{ inputs.arch }}-
  PROJECT_OPTIONS: target_arch ${{ inputs.arch }}
jobs:
  prepare:
    name: Prepare
    runs-on: 'ubuntu-24.04'
    outputs:
      cache-key-hash: ${{ steps.cache-key-hash.outputs.hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate cache key hash
        id: cache-key-hash
        shell: bash
        run: |
          : Generate cache key hash

          echo "hash=${{ hashFiles('project.conf', 'elements/**/*.bst', 'include/*', 'patches/**/*.patch', 'plugins/**/*.py') }}"  >> $GITHUB_OUTPUT

  fp-deps:
    needs: prepare
    uses: ./.github/workflows/build-fp-modules.yaml
    with:
      cache-key-prefix: flatpak-deps-bst-${{ inputs.arch }}-
      cache-key-hash: ${{ needs.prepare.outputs.cache-key-hash }}
      element: deps.bst
      modules: '["base", "devel", "devtools"]'
      arch: ${{ inputs.arch }}
      upload-artifacts: ${{ inputs.upload-artifacts }}
      reupload-cache: ${{ inputs.reupload-cache }}
