name: Push
run-name: ${{ github.ref_name }} push run
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build-project:
    name: Build Project
    uses: ./.github/workflows/build-project.yaml
