name: Refresh Cache
on:
  workflow_dispatch:
  schedule:
  - cron: 12 0 * * *

concurrency:
  # Purposefully put in the same group as push workflows to avoid race condition
  group: 'Push @ ${{ github.ref }}'

jobs:
  refresh-cache:
    name: Refresh Cache
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    uses: ./.github/workflows/build-project.yaml
    with:
      arch: ${{ matrix.arch }}
      reupload-cache: true
